### ISSUE TITLE
MongoDB para nuevas tecnologias de Sensores de datos (Caso de BOSH)

### ISSUE THREAD

**Issue by IoTeacher** [unidtj/mtics#7]
![](http://www.bosch-software-challenge.com/responsive_images/sm/bosch-logo.png)

La lectura de caso de esta compañia internacional con IoT en MongoDB

https://www.mongodb.com/customers/bosch

Redacta una relexión, recuerda que debes usar MARKDOWN hoy y siempre, para formatear las participaciones.

¿Que Gestor de Base de Datos usa FACEBOOK, AKAMAI (publidada de Google) y Kellogs ?

**Comment by Asened** [comment]
# Grupo Bosch  
## El Grupo Bosch  proveedor mundial de tecnología y servicios. 
Este comenzó como “Taller de mecánica de precisión e ingeniería eléctrica” ,en 1886 por Robert Bosch. Actualmente se encuentra como empresa líder de IoT.
Bosch ofrece soluciones innovadoras para hogares inteligentes, ciudades inteligentes, movilidad conectada e industria conectada. Utiliza su experiencia en tecnología de sensores, software y servicios, así como su propia nube IoT, para ofrecer a sus clientes soluciones conectadas entre dominios de una sola fuente. 
El objetivo estratégico del Grupo Bosch es ofrecer innovaciones para una vida conectada.

## ¿Que Gestor de Base de Datos usa FACEBOOK, AKAMAI (publidada de Google) y Kellogs ?
Facebook lo usan unos 1000 millones de personas en el mundo y utiliza un manejador de bases de datos creado para procesar la información gigantesca que millones de usuarios alimentan en el sistema.
Facebook  ha puesto ahora en código abierto un manejador llamado RocksDB, RocksDB está diseñado para cargas de trabajo embebido,  puede usarse para una base de datos cliente/servidor. RocksDB está construido sobre LevelDB para ser escalable y correr en servidores que tengan muchos núcleos. El benchmark y sus resultados se reportan en GitHub.

A través de MySQL, Facebook gestiona el almacenamiento de datos estructurados como publicaciones de muros, información de usuarios, biografías, etc. y los reproduce por las diferentes localizaciones geográficas de sus centros de bases de dato

Akamai Technologies, empresa que entrega una parte considerable del tráfico total de la Internet, utilizar una base de datos como servicio (DBaaS) en lugar de construir y correr su propia base de datos. Akamai seleccionó la DBaaS NoSQL de Cloudant, la cual se encuentra construida sobre Apache CouchDB. La DBaaS ha estado soportando la aplicación interna de administración de APIs por alrededor de 15 meses.  Las bases de datos de nube están ganando impulso en todas sus formas

**Comment by LeonardoEnriquezA** [comment]
<h1 style="text-align:center">Caso Bosch utilizando IOT</h1>
   
> Con el avance acelerado de las nuevas tecnologías, las empresas que están haciendo uso de ellas, están obteniendo mayor valor en sus procesos, tal es el caso de **Bosch**, a través del **Internet de las cosas IOT**, quien encabeza soluciones innovadoras en la industria. Bosch plantea un desafío importante, diseñar, desarrollar y operar soluciones de software, ayudando a clientes internos y externos.
 
## MongoDB
-------------
>   Conectando miles de dispositivos en linea y en tiempo real los procesos de la industria, se vuelve limitados y lentos utilizando base de datos estructuradas, esto debido al volumen, la velocidad y la complejidad de los datos que se generan. Con **MongoDB** esto puede ser solucionado. 

>   Al igual que Bosch, las empresas globales pueden aprovechar el IOT y el MongoDb para obtener enormes ventajas permitiendo monitorear cada una de las etapas de su modelo del negocio.

----------

## ¿Qué Gestor de Base de Datos usa **FACEBOOK, AKAMAI (publidada de Google) y Kellogs**?

>- **Facebook**, red social más grande en el mundo, gestiona su almacenamiento de datos estructurados por medio de MySQL. Sus bases de datos, se encuentran ubicadas en zonas geográficas distintas.


>- **AKAMAI**, corporación que provee, servicios para la entrega de contenidos de Internet, utiliza una base de datos como servicio (DBaaS) en vez de construir y ejecutar una base de datos propia. Esta empresa decidió utilizar la DBaaS NoSQL de Cloudant, la cual corre sobre Apache CouchDB. 

>- **Kellogs**, compañía multinacional agroalimentaria estadounidense, almacena sus datos en una base de datos Oracle.

**Comment by cesar-vaquera** [comment]
# **_Bosch & IoT_**
***
>La interacción entre los dispositivos tecnológicos cada vez es mas frecuente, manteniendonos mas enfocados en generar soluciones a cada necesidad que el hombre tiene. A medida que la información y las personas están conectadas, la tecnología sirve como herramienta de colaboración y toma de decisiones en un mundo en el que converge lo físico con lo digital
El IoT, en definitiva  es una de la principales tendencias hoy en día, tanto que quizás sea considerada como una revolución tecnológica tan grande como el inicio de da existencia de la web.
>
>El IoT, el manejo de los datos es mas valioso e importante que nunca, con esto como principal ideal, muchas de las empresas con enfoque tecnológico han optado por la mejora de la conectividad entre dispositivos aumentando la capacidad para almacenar y procesar datos, Gupo Bosch es una empresa que a adoptado esta nueva tendencia con la creación de nuevas aplicaciones que revolucionan las nuevas tecnologías, tal es el caso de la aplicación de sensores en el equipo de frenado en automóviles, con esto se recaba la información para almacenarla, gestionarla y analizarla en tiempo real dentro de una base de datos mediante MongoDB. 

# **_¿Cual gestor de BD utiliza Facebook, AKAMAI y Kellogs?_**
***
>**Facebook**, Un sistema como FaceBook maneja grandes cantidades de información relacional misma que los usuarios de este  alimentan diariamente. Para manejar la información Facebook utiliza un manejador de BD llamado ***RocksDB***, este se encuentra diseñado para cargas de trabajo embebido, este manejador se encuentra construido sobre ***LevelDB*** para ser escalable y ejecutarse sobre servidores con muchos núcleos.
>
>**AKAMAI**, esta empresa tecnológica entrega una parte considerable del tráfico total de la Internet diaria, se encuentra inclinada a resolver sus desafíos tecnológicos en casa. Akamai seleccionó la ******DBaaS NoSQL de Cloudant***, la cual se encuentra construida sobre Apache CouchDB. 
>
>**Kellogg's**, es el productor de cereales líder en todo el mundo y elabora principalmente alimentos para el desayuno, cereales y galletas. La compañía, con sede central en Michigan (EE.UU.), gestiona más de 586 productos y más de 67 marcas, y la fabricación de sus productos tiene presencia en 18 regiones y vende en 180 países. Kellogg's utiliza la tecnología ofrecida por  ***Stibo Systems***, mismo que  proporciona a las compañías un sistema de ***Gestión de Datos Maestros*** (MDM, por sus siglas en inglés), que permite hacer más eficiente el proceso de recolección de toda la información de los departamentos, centrándose en limpiar y gestionar los datos para proveerlos a otros sistemas de negocios.
***

**Comment by jmjackson** [comment]
# <i class="icon-file"></i> EL caso Bosch y MongoDB 

**Bosch** hasta el momento se ha considerado ser la punta de lanza en el internet de todas las cosas, cada dia **Bosch** integra mas y mas productos al IoT, y estos requieren acceso a datos en tiempo real.

Bosch integro la industria 4.0 y puso un area exclusiva para IoT y MongoDB como base de datos para poder acceder a toda esta información.

Bosch usa IoT en prácticamente todas sus áreas, desde la instrumentación de lineas de fabricación, detección de errores a través de millones de piezas, hasta poner sus dispositivos en 300 millones de vehículos para un proyecto telemático, todo esto lo ha realizado con la escalabilidad  de ***MongoDB Enterprise Advanced*** para poder dar vida  a todas sus soluciones de IoT.

![Mongo DB](https://mc.qcloudimg.com/static/img/8e139fdddacb073c3160a69355fbc63c/MongoDB.svg)


# Base de datos usados en FB,Akamai y Kellogs
-----	
## Akamai
Cuando subimos una foto en FB estos se gaurdan automaticamente en Akamai que es una empresa que gestiona contenidos multimedia a traves de CDN para que podamos acceder a esas fotos desde el servidor mas cercano, Akamai es usado por muchas empresas, incluso Amazon lo ha usado alguna vez. El motivo de su uso es el siguiente ellos usan un almacenamiento llamado Aura Object Store que es donde se guardan las fotos o videos  de los sitios multimedios como Facebook, Google,Microsoft,Apple entre Otros. Podemos decir que es una Base de datos replicador que funciona entre servidores para darnos un servicio mas rapido de descarga.
## Facebook
---
Por  su parte **Facebook** usa una base de datos llamada Rocks DB la cual gestiona contenidos en masa, y es escalable, actualmente el codigo de esta abierto y esta respaldada en GitHub para consultas y para poder contribuir en ese motor de Base de Datos. Esta base de datos esta hecha para soportar  cargas de trabajo embebidos pero tambien se puede usar como cliente/servidor, para su escalabilidad se hizo o esta construido sobre LevelDB.

## Kellogs
----

**Kellogs** por sus necesidades usa ***AWS (Amazon Web Services)*** ya que necesitaba acomodar terabytes de datos, y tener un servidor requeria mucha infraestructura y tiempo invertido. Entonces se vieron interesados en SAP Hana que es una base de datos en  memoria, 	y entonces invirtieron en AWS que ofrece un paquete completo de *SAP HANA* sobre una plataforma publica, la compañia ahora funciona con *SAP Accelerated Trade Promotion Planing* (TPM) patrocinado por *SAP HANA* y aprovechado por multiples instancias de AWS.

**Comment by anuartl** [comment]
## Bosch  
Comenta ser una empresa completamente inmersa en el IoT, siendo un conglomerado de más de 300,000 empleados conocida por sus aplicaciones en Estados Unidos, y un sólido enfoque a la evolución de sus sistemas y modelo de negocios.
Para enfrentar los complejos retos de la conectividad y calidad de servicio que demanda IoT se están apoyando con MongoDB, y por poner un ejemplo en el sector automovilístico la aplicación de Bosch en este ramo obtiene información del sistema de frenos, volante y limpia parabrisas para recolectar datos y poder hacer diagnósticos preventivos de mantenimiento y análisis de su rendimiento en campo.

## ¿Que Gestor de Base de Datos usa FACEBOOK, AKAMAI (publicidad de Google) y Kellogs?
Las grandes compañías usualmente utilizan una variedad de bases de datos, ya que funcionan para distintos propósitos, pero en el caso de Facebook, utiliza MySQL, Akamai utiliza DBaaS NoSQL, y Kellogs utiliza los servicios de AWS con una solución de SAP.

**Comment by MrAlonsoCervantes** [comment]
Lo que han mencionado anteriormente mis compañeros de clase nos da una clara perspectiva de porque Bosh está considerada como una empresa que se concentra en el futuro, y nos permite ver de forma clara que el uso de una base de datos específica contribuye al desarrollo de múltiples tareas, al administrar cantidades de datos.

De acuerdo a los altos directivos de Bosch, en determinado momento (en 2011) se buscó una solución estratégica para sus necesidades empresariales de manejo y administración de datos, la cual encontraron en Mongodb.

El valor de Mongo para Bosch radica en el cumplimiento de  3 factores específicos: agilidad, flexibilidad y escalabilidad.

Centraré mi atención en estos tres valores, sin dejar de lado uno muy importante que es la conectividad.

Es claro que la tendencia en aumento que ya podremos detener es una mayor velocidad de procesamiento de datos mediante redes más amplias y conexiones más potentes. Con el ingreso del 5G, se amplían las posibilidades de manejo y almacenamiento, ya que debemos tomar en cuenta que miles que los datos que se procesan, provienen de fuentes que se generan por millones de sensores en tiempo real.

Es lógico pensar que BOSH encuentre soluciones para su administración de datos en MongoDB la cual posee todas las cualidades que permiten una clara visión unificada, de procesos y eventos específicos.

AGILIDAD:

En el caso de BOSCH, un claro ejemplo de AGILIDAD EN PROCESAMIENTO DE DATOS corresponde a la detección de colisiones automovilísticas, a través del uso de sensores ubicados estratégicamente en la carrocería, lo cual permite detectar con mayor facilidad, un accidente, hacer uso de localización mediante satélites, y enviar la asistencia necesaria al punto exacto donde sea requerido.

FLEXIBILIDAD

BOSCH no solo ha encontrado al colaborador perfecto en MONGODB, si no que además, puede implementar nuevos acercamientos y planteamientos de solución en diferentes industrias. Desde emarketing, hasta crear soluciones para mejorar las condiciones ambientes de trabajo, o incluso dentro del campo de la agricultura.

Es importante mencionar que BOSCH considera que MONGODB no solo es un proveedor de tecnología, si no como una empresa que lidera en la innovación de productos de software, potenciando y ampliando la posibilidades del uso del IoT (ENTORNET), en todos los campos de la ciencia.


ESCALABILIDAD

Cuando hablamos de escalabilidad  no es lo mismo a nivel de desarrollo de software que del desarrollo de un negocio. En ambos casos lo que se busca es: escalar. En cuanto a negocio BOSCH considera que la alianza con MONGODB es estratégica, al ser esta un empresa de avanzada en el futuro dominio del ENTORNET en el mundo de los negocios. 

Ahora bien la calidad en relación con el desarrollo de software, tiene que ver con la capacidad de manejar y administrar grandes cantidades de datos y de información de forma integral y coherente, es decir, optima.

Con cada nueva generación de “objetos” vienen nuevas generaciones de sensores, los cuales generan nuevos datos, y nuevas necesidades de procesamiento y administración.

MONGODB, no solo permite que la escalabilidad, sino que propone crecimiento de negocio mediante la adopción de mecanismos flexibles y un estructura de software para manejar aplicaciones que requieren de un óptimo manejo de volúmenes de datos capturados por los más de 40 billones de sensores, que actualmente existen, los cuales se espera lleguen a más del doble para el 2020.

https://es.slideshare.net/mongodb/internet-of-things-with-bosch-from-concept-to-code

https://www.mongodb.com/customers/bosch

**Comment by MrAlonsoCervantes** [comment]
FACEBOOK: 
Facebook opta por el uso de una Base de Datos open source, ROCKSDB, la cual ha sido desarrollada por dicha compañía en el 2015.  Al ser de codigo abierto, abre la puerta a la contribucion, utilizando Github, a cualquiera que desee contribuir.

http://www-conf.slac.stanford.edu/xldb2015/Talks2015/LT_4_SiyingDong_MyRocks_XLDB.pdf

**Comment by MrAlonsoCervantes** [comment]
AKAMAI es un proveedor de CDN (Content Delivery Network) que lidera a nivel mundial en el campo de la informatica. 
El origen de Akamai parte del desafío que planteó Tim Berners-Lee, el inventor de la World Wide Web, en el Instituto de Tecnología de Massachusetts (MIT) a principios de 1995. El padre de la web predijo la congestión que no tardaría en resultar tan familiar a los usuarios de Internet y retó a sus colegas del MIT a inventar una forma básicamente nueva y mejor de distribuir contenidos de Internet. Lo que posiblemente no anticipó es que plantear el problema en un entorno académico podría dar lugar a un servicio comercial que ha revolucionado Internet

**Comment by MrAlonsoCervantes** [comment]
Kellogs es una compañia lider en el serctor de productos alimenticios, cereales sobre todo.

https://aws.amazon.com/solutions/case-studies/kellogg-company/

Por qué Amazon Web Services

Kellogg necesitaba una solución que pudiera acomodar terabytes de datos, escalar de acuerdo con las necesidades de infraestructura y mantenerse dentro de su presupuesto. La compañía se interesó en una solución de SAP llamada Aceleración de la Planificación de la Promoción del Comercio, que funciona con SAP HANA, la plataforma de tecnología de base de datos en memoria de SAP. Amazon Web Services (AWS) ofrece un entorno HANA totalmente certificado por SAP en una plataforma de nube pública. Debido a que SAP trabaja en AWS Cloud, la compañía sabía que podía alcanzar la velocidad, el rendimiento y la agilidad que requería sin realizar una inversión significativa en hardware físico. Kellogg decidió comenzar de inmediato con entornos de prueba y desarrollo para sus operaciones en EE. UU.

La compañía ahora está ejecutando la solución SAP Accelerated Trade Promotion Management (TPM), con tecnología de SAP HANA y aprovechando múltiples tipos de instancias de AWS tanto para la aplicación de SAP como para las capas de la base de datos de HANA. Estas instancias de Amazon Elastic Compute Cloud (Amazon EC2) procesan 16 TB de datos de ventas semanalmente a partir de promociones en los EE. UU., Y modelan docenas de simulaciones de datos por día.

La compañía también utiliza la nube privada virtual de Amazon (Amazon VPC), que está conectada directamente a los centros de datos de Kellogg para permitir el acceso a SAP TPM directamente para los empleados que están en la red de la compañía. El servicio de almacenamiento simple de Amazon (Amazon S3) se utiliza para copias de seguridad de datos, incluidos los volúmenes de IOPS provisionados (P-IOPS) de Amazon Elastic Block Store (Amazon EBS) para el almacenamiento. La empresa registra eventos utilizando AWS Identity and Access Management (AWS IAM).

Kellogg usa Amazon CloudWatch para monitoreo, lo que ayuda a la compañía a asignar costos a cada departamento en función de su uso de infraestructura individual. "CloudWatch ayuda a nuestra gente a tomar mejores decisiones sobre la capacidad que necesitan, para que puedan evitar el desperdicio", dice McIlwain. "Nunca pudimos hacer eso con nuestra infraestructura local. AWS desglosa el uso y el costo a tal nivel granular que podemos identificar qué costos provienen de cada departamento, como un modelo de peaje. "Los costos y beneficios de este servicio de TI ahora se pueden alinear para que Kellogg pueda evaluar el verdadero retorno de la inversión.

Para una alta disponibilidad, Kellogg aprovecha múltiples zonas de disponibilidad AWS (AZ) sin el costo adicional de mantener un espacio separado

**Comment by MrAlonsoCervantes** [comment]
`**Comment**`
