### ISSUE TITLE
Repaso semana 2: Restaurar BD, git y consultas sencillas

### ISSUE THREAD

**Issue by IoTeacher** [unidtj/mtics#8]
Repaso de BD: 

AWS, Git y SQL Basicos

¿Cuantas mujeres son empleadas? en porcentaje
¿Nomina de los hombre es por $?
¿Cuanto gana Juan Perez?

$ mysql -u root -p
mysql> . _....aqui va la consulta_

**Comment by IoTeacher** [comment]
Sea la BD de https://dev.mysql.com/doc/employee/en/employees-installation.html

La llave esta publicada

**Comment by IoTeacher** [comment]
![screen shot 2017-11-11 at 8 25 34 am](https://user-images.githubusercontent.com/2523851/32691234-07a830fc-c6b9-11e7-9f4b-7b5b20b5989c.png)


Sus servidores, contestar las preguntas anteriores

**Comment by IoTeacher** [comment]
PAra conectarnos a Windows
https://www.youtube.com/watch?v=dZyFzUvJQMc

Para mac o Linux
https://www.youtube.com/watch?v=3xJeGBTm5LE

**Comment by anuartl** [comment]
#¿Cuantas mujeres son empleadas? en porcentaje
Muejres 40% Hombres 60% 🥇

**Comment by IoTeacher** [comment]
TUTORIAL para MYSQL Basico en
http://sqlzoo.net/

**Comment by LeonardoEnriquezA** [comment]
+--------------+
| sum(salary)  |
+--------------+
| 181480757419 |
+--------------+

**Comment by IoTeacher** [comment]
Cuantos empleados cumplen años este noviembre y quiene hoy para enviarle su correo de felicitacion y un bono $1,000 con reservacion en Hotel Rosarito 3d2n, todo pagado suite presidencial.

**Comment by jmjackson** [comment]
+---------+--------------+
| genero  | salario      |
+---------+--------------+
| 1706321 | $108,928,421,890 |
+---------+--------------+
suma de salarios

**Comment by IoTeacher** [comment]
select CONCAT("Felicidades " , first_name , " " , last_name,  "en su cumpleaños, tiene Ud. un bono de
 por $1000 y reservación HR presidencial ") as MensajeEjecutivoNOV
from employees
where month(birth_date) = 11 and day(birth_date) = 11; 


select "Cuantos cumplen en noviembre ", count(birth_date)
from employees
where month(birth_date) = 11;
